name: Node.js CI

# Trigger workflow on push or pull request events on master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Check out the repository code
      - uses: actions/checkout@v2
      
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use a more recent Node.js version

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run linter
        run: npm run lint 

      # Run tests
      - name: Run tests
        run: npm test  # This should work if Jest is set up
